keys:
  - &admin-dotboris age16lldqqyqqy6rw4zerw6kxr5x8dygt8apag8ve7n42n6me74mk4nseyvm3l
  - &host-homelab age1k6y7mzx6tpj9g0aqwww4zgtxjkk5ja5dw68nc26528296eyykq5qahk2yt
  - &host-homelab-test age1uxn8hz7fv4h05l4uhtshpxkylv4krfmekc8ancuur682djmnm9asmgs8ma

creation_rules:
  - path_regex: '^hosts/homelab/secrets.sops.yaml$'
    key_groups:
      - age:
          - *admin-dotboris
          - *host-homelab

  - path_regex: '^hosts/homelab-test/secrets.sops.yaml$'
    key_groups:
      - age:
          - *admin-dotboris
          - *host-homelab-test

stores:
  yaml:
    indent: 2