keys:
  - &backup age14h3mwuj74khf4vu75a9mqy7hawc2pej8yqrqw5g55qcx6djup55qydcvmc
  - &admin-dotboris-desktop ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJSVAavmM8Tz004E0GYZBerdouuquNldm8yozz76ZUw8
  - &admin-dotboris-foxtrot ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9QlBQ++xvislNNi4L2hkYpNHBL6MjrAkVhMRhUrOtg
  - &host-homelab age1drttm3pedzu63pwahgfjk0f2za0ywu57dec0e5sh3nc59vfm55xqzph4zm
  - &host-homelab-test age1uxn8hz7fv4h05l4uhtshpxkylv4krfmekc8ancuur682djmnm9asmgs8ma

creation_rules:
  - path_regex: '^hosts/homelab/secrets.sops.yaml$'
    key_groups:
      - age:
          - *backup
          - *admin-dotboris-desktop
          - *admin-dotboris-foxtrot
          - *host-homelab

  - path_regex: '^hosts/homelab-test/secrets.sops.yaml$'
    key_groups:
      - age:
          - *backup
          - *admin-dotboris-desktop
          - *admin-dotboris-foxtrot
          - *host-homelab-test

stores:
  yaml:
    indent: 2
