# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{...}: {
  flake.hosts.homelab.module = {
    config,
    lib,
    modulesPath,
    ...
  }: {
    imports = [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];
    boot = {
      initrd = {
        availableKernelModules = ["xhci_pci" "ahci" "usb_storage" "sd_mod"];
        kernelModules = ["dm-snapshot"];
      };
      kernelModules = ["kvm-intel"];
      extraModulePackages = [];
    };

    swapDevices = [];

    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
